<?php

/**
 * Default home page view
 *  
 * @author
 * @version
 */

$this->headTitle('Home');
?>
<div id="description">
	<h3>Welcome to boodah.net</h3>
	<p>It's been a long time since I worked on my own site, the older version was looking a little worse for wear.
	My goal for this new version is to centralise all my work into one place.</p>
	<p>You'll find news articles I've <a href="/social/news">Dugg</a>, <a href="/projects">projects</a> that I'm working on, not to mention the latest <a href="/blog">articles</a> I've published on Wordpress.</p>
</div>