<?php

/**
 * Default blog page
 * 
 * Lists all the latest blog enteries
 *  
 * @author Yomi (baphled boodah) Colledge <baphled@boodah.net>
 * @version 0.2
 * 
 */

$this->headTitle('Baphled Boodah Weblog');

if(is_array($this->items)) {
	foreach($this->items as $item): ?>
		<div class="chunk">
			<div id="main-content-header">
		    	<div id="content-title" class="title" >
		    		<a class="header" href="<?=$item->get_permalink()?>" target="_blank"><?php echo $item->get_title(); ?></a>
		    	</div>
		    </div>
		    <span id="blog_date"><?php echo $item->get_date('j M Y'); ?></span>
			<div id="description"><?= $item->get_description(); ?></div>
			<p class="footnote favicons" align="center">
				<a href="<?php echo $item->add_to_blinklist(); ?>" title="Add post to Blinklist"><img src="/images/favicons/blinklist.png" alt="Blinklist" /></a>
				<a href="<?php echo $item->add_to_blogmarks(); ?>" title="Add post to Blogmarks"><img src="/images/favicons/blogmarks.png" alt="Blogmarks" /></a>
				<a href="<?php echo $item->add_to_delicious(); ?>" title="Add post to del.icio.us"><img src="/images/favicons/delicious.png" alt="del.icio.us" /></a>
				<a href="<?php echo $item->add_to_digg(); ?>" title="Digg this!"><img src="/images/favicons/digg.png" alt="Digg" /></a>
				<a href="<?php echo $item->add_to_magnolia(); ?>" title="Add post to Ma.gnolia"><img src="/images/favicons/magnolia.png" alt="Ma.gnolia" /></a>
				<a href="<?php echo $item->add_to_myweb20(); ?>" title="Add post to My Web 2.0"><img src="/images/favicons/myweb2.png" alt="My Web 2.0" /></a>
				<a href="<?php echo $item->add_to_newsvine(); ?>" title="Add post to Newsvine"><img src="/images/favicons/newsvine.png" alt="Newsvine" /></a>
				<a href="<?php echo $item->add_to_reddit(); ?>" title="Add post to Reddit"><img src="/images/favicons/reddit.png" alt="Reddit" /></a>
				<a href="<?php echo $item->add_to_segnalo(); ?>" title="Add post to Segnalo"><img src="/images/favicons/segnalo.png" alt="Segnalo" /></a>
				<a href="<?php echo $item->add_to_simpy(); ?>" title="Add post to Simpy"><img src="/images/favicons/simpy.png" alt="Simpy" /></a>
				<a href="<?php echo $item->add_to_spurl(); ?>" title="Add post to Spurl"><img src="/images/favicons/spurl.png" alt="Spurl" /></a>
				<a href="<?php echo $item->add_to_wists(); ?>" title="Add post to Wists"><img src="/images/favicons/wists.png" alt="Wists" /></a>
				<a href="<?php echo $item->search_technorati(); ?>" title="Who's linking to this post?"><img src="/images/favicons/technorati.png" alt="Technorati" /></a>
			</p>
		</div>
	<?php endforeach; }